image: maven:3-jdk-13

checkstyle:
    script: "mvn checkstyle:checkstyle"


compile:
  script: "mvn -f code/pom.xml clean compile test-compile -B"
  
test: 
    script: " mvn -f code/pom.xml clean test -B"
   
