image: maven:3-jdk-13

checkstyle:
    script: "cd back_end; mvn checkstyle:checkstyle"


compile:
  script: "cd back_end; mvn clean compile test-compile -B"
  
test: 
    script: "cd back_end; mvn clean test -B"
   
