image: maven:3-jdk-13

checkstyle:
    script: "cd back_end; mvn checkstyle:checkstyle"
compile:
  script: "cd back_end; mvn clean compile test-compile -B"
  
test: 
    script: 
        - "cd back_end; mvn clean test -B"
        - awk -F"," '{ instructions += { }'
           + $5; covered += $5 
        } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered"  }' target/jacoco/jacoco.csv'
    artifacts:
        paths:
            -target/site/jacoco/
   
